version: '3'
services:
  qbittorrent:
    image:  wernight/qbittorrent:latest
    restart: 'always'
    ports:
      - CUSTOM_PORT_TCP:8080 
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - ./volumes/config:/config
      - ./volumes/torrents:/torrents
      - ./volumes/downloads:/downloads