version: '3'

services:

  portainer:
    image: portainer/portainer:latest
    restart: 'always'
    ports:
      - CUSTOM_PORT:9000
    volumes:
       - 'portainer-volume:/data'
       - '/var/run/docker.sock:/var/run/docker.sock:rw'

volumes:
  portainer-volume: