version: "3"
services:
  aion_smartminer:
    image: blavorata/aion_smartminer:latest
    restart: 'always'
    environment:
     -  MINING_POOL_ADDRESS=CUSTOM_MINING_POOL_ADDRESS
     -  MINING_POOL_PORT=CUSTOM_MINING_POOL_PORT
     -  MINING_ADDRESS=CUSTOM_MINING_ADDRESS
     -  CUDA_SOLVER=CUSTOM_CUDA_SOLVER
     -  DEVICE=CUSTOM_DEVICE
networks:
  default:
    external:
      name: CUSTOM_NETWORK