# 5601 (Kibana web interface).
# 9200 (Elasticsearch JSON interface).
# 5044 (Logstash Beats interface, receives logs from Beats such as Filebeat – see the Forwarding logs with Filebeat section).
version: '2'
services:
  elk:
    image: sebp/elk:564
    restart: 'always'
    volumes:
      - ./plugins:/etc/plugins
    ports:
      - '5601:5601'
      - '9200:9200'
      - '5044:5044'