version: '2'
services:
  cloud9:
    image: sapk/cloud9:latest
    restart: 'always'
    command: '--auth CUSTOM_LOGIN:CUSTOM_PASSWORD'
    ports:
      - CUSTOM_PORT:8181
    user: "CUSTOM_UID:0"
    volumes:
       - '~/:/workspace'