version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './mariadb_data:/bitnami'
  owncloud:
    image: 'bitnami/owncloud:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './owncloud_data:/bitnami'
    depends_on:
      - mariadb