version: '2.2'
services:
  rtmp_nginx:
    container_name: rtmp_nginx
    image: jasonrivers/nginx-rtmp:latest
    restart: 'always'
    environment:
      RTMP_STREAM_NAMES: CUSTOM_RTMP_STREAM_NAMES
      #RTMP_PUSH_URLS: rtmp://live.youtube.com/myname/streamkey,rtmp://live.twitch.tv/app/streamkey
    ports:
      - CUSTOM_RTMP_PORT:1935
      - CUSTOM_HLS_PORT:8080