version: '3.3'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: CUSTOM_RESTART_POLICY
    hostname: 'CUSTOM_HOST_NAME'
    ports:
      - 'CUSTOM_PORT_HTTP:80'
      - 'CUSTOM_PORT_HTTPS:443'
      - 'CUSTOM_PORT_SSH:22'
    volumes:
      - './volumes/gitlab/config:/etc/gitlab'
      - './volumes/gitlab/logs:/var/log/gitlab'
      - './volumes/gitlab/data:/var/opt/gitlab'
    environment:
        - VIRTUAL_PORT=CUSTOM_VIRTUAL_PORT
        - VIRTUAL_HOST=CUSTOM_VIRTUAL_HOST
        - LETSENCRYPT_HOST=CUSTOM_LETSENCRYPT_HOST
        - LETSENCRYPT_EMAIL=CUSTOM_LETSENCRYPT_EMAIL
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://CUSTOM_HOST_NAME:CUSTOM_PORT_HTTP'
        gitlab_rails['gitlab_shell_ssh_port'] = CUSTOM_PORT_SSH
        # Add any other gitlab.rb configuration here, each on its own line
    networks:
      - webproxy
      
networks:
  webproxy:
    external:
      name: webproxy