version: '3'

services:

  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - CUSTOM_MONGODB_PORT:27017
    volumes:
      - mongodb-volume:/bitnami
    environment:
      MONGODB_ROOT_PASSWORD: CUSTOM_MONGODB_ROOT_PASSWORD
      MONGODB_USERNAME: CUSTOM_MONGODB_USERNAME
      MONGODB_PASSWORD: CUSTOM_MONGODB_PASSWORD
      MONGODB_DATABASE: CUSTOM_MONGODB_DATABASE

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - CUSTOM_ADMIN_PORT:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: CUSTOM_ADMIN_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: CUSTOM_ADMIN_PASS
      
volumes:
  mongodb-volume:

  #https://github.com/bitnami/bitnami-docker-mongodb