version: '3'
services:
  postgres:
    image: 'postgres:9.5'
    restart: 'always'
    ports:
      - 'CUSTOM_DB_PORT:5432'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=CUSTOM_ODOO_DB_USER
      - POSTGRES_PASSWORD=CUSTOM_ODOO_DB_PASSWORD
      
  odoo:
    image: 'elicocorp/odoo-china:11.0'
    restart: 'always'
    command: start
    ports:
      - 'CUSTOM_ODOO_PORT:8069'
    volumes:
      - './odoo_data/filestore:/opt/odoo/data/filestore'
      - './odoo_data/sessions:/opt/odoo/data/sessions'
      - './odoo_data/additional_addons:/opt/odoo/additional_addons'
      - './odoo_data/specific_addons:/opt/odoo/specific_addons'
      - './odoo_data/etc:/opt/odoo/etc'
    links:
      - 'postgres:db'
    environment:
      - ODOO_ADMIN_PASSWD=CUSTOM_ODOO_ADMIN_PASSWD
      - ODOO_DB_USER=CUSTOM_ODOO_DB_USER
      - ODOO_DB_PASSWORD=CUSTOM_ODOO_DB_PASSWORD
      - FETCH_OCA_DEPENDENCIES=False