version: '3'

services:

  shadowsocks:
    image: 'mritd/shadowsocks:latest'
    restart: 'always'
    environment:
      - SS_CONFIG=-s 0.0.0.0 -p 6443 -m aes-256-cfb -k CUSTOM_PASSWORD --fast-open
      - KCP_MODULE=kcpserver
      - KCP_CONFIG=-t 127.0.0.1:6443 -l :6500 -mode fast2
      - KCP_FLAG=true
    ports:
      - 'CUSTOM_PORT_TCP:6443'
      - 'CUSTOM_PORT_UDP:6500/udp'