version: '3'

services:

  ijs:
    image: nikhilk/ijs
    restart: always
    # We do not want to expose ports publicly, so we comment this part 
    # But we note that the native port of mattermost is 8065, which is only 
     # available on the virtual network "webproxy" where the proxy is also connected
    ports:
     - CUSTOM_PORT_HTTP:9999
    volumes:
      - ./volumes/data:/data
    #environment:
    #  - VIRTUAL_PORT=8888
    #  - VIRTUAL_HOST=domain.com
    #  - LETSENCRYPT_HOST=domain.com
    #  - LETSENCRYPT_EMAIL=admin@domain.com
    #networks:
    #  - webproxy

#networks:
#  webproxy:
#    external:
#      name: webproxy
