version: '3.1'
services:
  eclipse_che:
    image: eclipse/che:latest
    restart: always
    command: start
    user: 1000:1000
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/:/data
      
#https://www.eclipse.org/che/docs/docker-single-user.html