version: '2'
services:
  portainer:
    image: portainer/portainer:latest
    restart: 'always'
    ports:
      - 9000:9000
    volumes:
       - './portainer_data:/data'
       - '/var/run/docker.sock:/var/run/docker.sock'